name: Relaase

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Job
    steps:
      - uses: actions/checkout@v2
      - uses: schmidtw/hello-world-composite-action@v2
        name: Generate Release
        id: generate_release
        with:
          artifact-dir: foobar
          verbose: 1
          meson-wrap: true
