name: Relaase

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release Job
    steps:
      - uses: actions/checkout@v2
      - uses: schmidtw/hello-world-composite-action@v2.0.1
        name: Generate Release
        id: generate_release
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.generate_release.outputs.release-name }}
          draft: false
          prerelease: false
          bodyFile: ${{ steps.generate_release.outputs.release-body }}
          artifacts: "artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
